#!/usr/bin/env python3
"""folder-index.py — generate INDEX.md in every big folder, and check that every folder
an agent may land in has an AGENTS.md.

Why: the root AGENTS.md is one page for the whole repo. An agent (or Arya) opening
`iOS/` or `scripts/` still has to guess which of 30–125 files matters. Each big folder
gets a generated INDEX.md — one line per file or sub-folder, with the purpose the file
states about itself — so the reader spends ~40 tokens per row instead of opening files.
The per-folder AGENTS.md next to it is hand-written judgment: read-first, serialized
files, the command that proves a change, traps. This script never writes AGENTS.md.

Purpose lines are the file's own header comment (code, same rule as codemap-index.py),
the first H1 of a markdown file, or the `description:` of a SKILL.md. Sub-folder rows
take the H1 of that folder's AGENTS.md. Deterministic: no dates, sizes are buckets, so
`--check` can diff and go red exactly when something is stale.

Usage:  python3 scripts/folder-index.py          # (re)write every INDEX.md
        python3 scripts/folder-index.py --check  # exit 1 if an INDEX.md is stale/missing
                                                 # or a required AGENTS.md is missing
"""
import importlib.util
import os
import re
import sys

# codemap-index.py has a hyphen, so load it by path and reuse its helpers (one purpose rule).
_spec = importlib.util.spec_from_file_location(
    "codemap_index", os.path.join(os.path.dirname(os.path.abspath(__file__)), "codemap-index.py")
)
_cm = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_cm)
ROOT, bucket, git_files, is_code, purpose_of, read = _cm.ROOT, _cm.bucket, _cm.git_files, _cm.is_code, _cm.purpose_of, _cm.read

BIG = 8  # direct children (files + sub-folders) from which a folder gets an INDEX.md
MEDIA = (".png", ".jpg", ".jpeg", ".gif", ".mov", ".mp4", ".svg", ".webp", ".heic", ".pdf")
HEADER = (
    "*Generated by `python3 scripts/folder-index.py`; do not edit. "
    "Read this, pick ONE file, open only that. "
    "Judgment (read-first, traps, how to prove a change) is in [AGENTS.md](AGENTS.md).*"
)


def dirs_of(files):
    out = {}
    for p in files:
        parts = p.split("/")
        for i in range(1, len(parts)):
            out.setdefault("/".join(parts[:i]), []).append(p)
    return out


def children(d, files):
    direct_files, subdirs = [], {}
    for p in files:
        rest = p[len(d) + 1 :]
        if "/" in rest:
            subdirs.setdefault(rest.split("/")[0], []).append(p)
        else:
            direct_files.append(rest)
    return sorted(direct_files), subdirs


def h1_of(text):
    for line in text.splitlines()[:30]:
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def frontmatter_desc(text):
    if not text.startswith("---"):
        return ""
    m = re.search(r"^description:\s*(.+)$", text, re.M)
    return m.group(1).strip().strip('"').strip("'") if m else ""


def tidy(name, s):
    s = re.sub(r"^" + re.escape(name) + r"/?\s*(—|-|:)\s*", "", s)
    s = re.sub(r"^" + re.escape(name.split(".")[0]) + r"/?\s*(—|-|:)\s*", "", s)
    if len(s) > 140:
        s = s[:140].rsplit(" ", 1)[0] + "…"
    return s.replace("|", "\\|")


def file_purpose(path):
    name = os.path.basename(path)
    if path.endswith(MEDIA):
        return ""
    try:
        text = read(path)
    except OSError:
        return ""
    if name == "SKILL.md":
        return tidy(name, frontmatter_desc(text) or h1_of(text))
    if path.endswith((".md", ".mdc")):
        return tidy(name, h1_of(text) or frontmatter_desc(text))
    if is_code(path):
        return tidy(name, purpose_of(path, text))
    return ""


def dir_purpose(d, sub_files):
    for cand in ("AGENTS.md", "SKILL.md", "README.md"):
        p = d + "/" + cand
        if p in sub_files:
            text = read(p)
            return tidy(os.path.basename(d), frontmatter_desc(text) if cand == "SKILL.md" else h1_of(text))
    return ""


def render(d, files):
    direct, subdirs = children(d, files)
    rows = []
    for name, sub in sorted(subdirs.items()):
        rows.append(f"| `{name}/` | {len(sub)} files | {dir_purpose(d + '/' + name, set(sub))} |")
    for name in direct:
        if name in ("INDEX.md",):
            continue
        p = d + "/" + name
        size = ""
        if not p.endswith(MEDIA):
            try:
                size = bucket(read(p).count("\n"))
            except OSError:
                size = ""
        rows.append(f"| `{name}` | {size} | {file_purpose(p)} |")
    return (
        f"# {d}/ — index\n\n{HEADER}\n\n| entry | size | what it is |\n|---|---|---|\n" + "\n".join(rows) + "\n"
    )


def under_skill(d, tree):
    """True when any ancestor folder (or d itself) is a skill folder: its SKILL.md is the map."""
    parts = d.split("/")
    for i in range(1, len(parts) + 1):
        anc = "/".join(parts[:i])
        if anc + "/SKILL.md" in tree.get(anc, []):
            return True
    return False


def wants_index(d, files, tree=None):
    direct, subdirs = children(d, files)
    if len(direct) + len(subdirs) < BIG:
        return False
    if tree is not None and under_skill(d, tree):
        return False
    if re.match(r"^\.(claude|cursor)/commands(/|$)", d):
        return False  # every .md there is a slash command; an INDEX.md would become /INDEX
    media = sum(1 for f in direct if f.endswith(MEDIA))
    return media < 0.8 * max(len(direct), 1)  # a folder of screenshots needs AGENTS.md, not a table


# AGENTS.md is required in every tracked folder except the self-describing or trivial ones.
def needs_agents_md(d, files):
    depth = d.count("/") + 1
    names = {os.path.basename(f) for f in files}
    if "SKILL.md" in names and depth > 1:
        return False  # a skill folder is its own brief
    if re.search(r"(^|/)\d{4}-\d{2}", d):
        return False  # dated record folders
    if any(seg in ("runs", "vendor", "migrations", "node_modules", "workflows") for seg in d.split("/")):
        return False
    if ".xcassets" in d or "/references" in d or "/specs" in d or "/man" in d:
        return False
    if d.startswith("install/payload/share/skills/") or d.startswith("docs/overnight"):
        return False
    if d == "graphify-out":
        return False  # generated; only GRAPH_REPORT.md is tracked and the rest is gitignored
    if re.match(r"^\.(claude|cursor)/commands(/|$)", d):
        return False  # every .md in a commands/ folder is a slash command; a brief there becomes /AGENTS
    if depth >= 2 and len(files) < 3:
        return False  # tiny leaf
    return True


def ignored(paths):
    """The subset of paths .gitignore would drop: a brief or index there could never be
    committed, so a fresh clone or CI must not be asked for it."""
    if not paths:
        return set()
    import subprocess
    r = subprocess.run(["git", "-C", ROOT, "check-ignore", "--stdin"], input="\n".join(paths), text=True, capture_output=True)
    return set(r.stdout.split())


def main():
    check = "--check" in sys.argv
    files = git_files()
    tree = dirs_of(files)
    stale, missing = [], []
    skip = ignored([d + "/AGENTS.md" for d in tree] + [d + "/INDEX.md" for d in tree])
    for d, sub in sorted(tree.items()):
        if d + "/AGENTS.md" not in skip and needs_agents_md(d, sub) and d + "/AGENTS.md" not in sub and not os.path.exists(os.path.join(ROOT, d, "AGENTS.md")):
            missing.append(d + "/AGENTS.md")
        if d + "/INDEX.md" in skip or not wants_index(d, sub, tree):
            continue
        want = render(d, sub)
        out = os.path.join(ROOT, d, "INDEX.md")
        have = open(out, encoding="utf-8").read() if os.path.exists(out) else None
        if check:
            if have != want:
                stale.append(d + "/INDEX.md")
        elif have != want:
            with open(out, "w", encoding="utf-8") as f:
                f.write(want)
            print("wrote", d + "/INDEX.md")
    if check:
        for s in stale:
            print("folder-index: STALE", s)
        for m in missing:
            print("folder-index: MISSING", m)
        if stale or missing:
            print("folder-index: run `python3 scripts/folder-index.py` for INDEX.md; write the missing AGENTS.md by hand")
            sys.exit(1)
        print("folder-index: ok")
    elif missing:
        print("folder-index: still missing AGENTS.md in:", ", ".join(missing))


if __name__ == "__main__":
    main()
